import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

/* ===========================================================================
   Security headers
   ---------------------------------------------------------------------------
   This site sent none of these for its whole life, and nothing noticed, because
   a page with no `X-Content-Type-Options` renders exactly like a page with one.
   That is the shape of failure these tests are for: not "does it break" but
   "did it quietly stop being true".

   There are two surfaces and they are answered by different things. The Worker
   answers routes; Cloudflare's static asset handler answers `/assets/*`,
   `/demos/*`, `/fun/*` and `/derived/*` *before* the Worker is invoked, so a
   policy set only in `worker/index.ts` lands on the HTML and misses the
   stylesheet, the client bundle and the vendored application in the iframe. Both
   halves are checked here: the Worker by rendering through it, and the asset side
   by reading the `_headers` file the build writes.

   `scripts/security-headers.mjs` is the other half of this again — it proves the
   headers are on the wire and that nothing on the page is blocked by them, which
   needs a real browser and a real preview server.
   =========================================================================== */

const read = (path) => readFile(new URL(path, import.meta.url), "utf8");

/** Renders any path through the built worker. */
async function renderPath(pathname) {
  const workerUrl = new URL("../dist/server/index.js", import.meta.url);
  workerUrl.searchParams.set("test", `${process.pid}-${Date.now()}-${pathname}`);
  const { default: worker } = await import(workerUrl.href);

  return worker.fetch(
    new Request(`http://localhost${pathname}`, { headers: { accept: "text/html" } }),
    { ASSETS: { fetch: async () => new Response("Not found", { status: 404 }) } },
    { waitUntil() {}, passThroughOnException() {} },
  );
}

const REQUIRED = [
  "content-security-policy",
  "x-content-type-options",
  "x-frame-options",
  "referrer-policy",
  "permissions-policy",
  "strict-transport-security",
];

test("every response the worker returns carries the security headers", async () => {
  for (const pathname of ["/", "/legal", "/legal/totem/privacy", "/does-not-exist"]) {
    const response = await renderPath(pathname);
    for (const header of REQUIRED) {
      assert.ok(
        response.headers.get(header),
        `${pathname} came back without ${header}`,
      );
    }
  }
});

test("the static assets get the same headers, from _headers", async () => {
  /* `dist/client/_headers` is generated by `build/security-headers-vite-plugin.ts`
     from the same module the worker imports, so this is checking that the build
     wrote it rather than that somebody kept two copies in step. */
  const headersFile = await read("../dist/client/_headers");

  for (const header of REQUIRED) {
    assert.match(
      headersFile,
      new RegExp(`^\\s{2}${header}:`, "im"),
      `_headers does not set ${header}, so ${header} is missing from every asset`,
    );
  }

  assert.match(headersFile, /^\/\*$/m, "the rules are not applied to every path");

  /* vinext writes this file itself when it is absent, to make the content-hashed
     bundles immutable. The plugin replaces that file, so it has to carry the rule
     forward or a year of caching disappears silently. */
  assert.match(headersFile, /^\/assets\/\*$/m);
  assert.match(headersFile, /Cache-Control: public, max-age=31536000, immutable/);
});

test("framing and the microphone are set for a page that embeds an application", async () => {
  /* The two values a later tightening would get wrong, and both fail silently.
     Choir Practice is the real application in a same-origin `<iframe>`, and its
     pitch guidance listens to you sing. `X-Frame-Options: DENY` and
     `frame-ancestors 'none'` forbid same-origin framing too, so either would leave
     that section an empty box; `microphone=()` overrides the iframe's own `allow`
     rather than negotiating with it.

     Comments stripped first: the note above those values names the wrong ones in
     order to explain why they are wrong, and a check that reads prose as policy
     would make that explanation unwritable. */
  const source = (await read("../worker/security-headers.ts")).replace(
    /\/\*[\s\S]*?\*\/|\/\/.*$/gm,
    " ",
  );

  assert.match(source, /frame-ancestors 'self'/);
  assert.doesNotMatch(source, /frame-ancestors 'none'/);
  assert.match(source, /"X-Frame-Options": "SAMEORIGIN"/);
  assert.match(source, /microphone=\(self\)/);
  assert.match(source, /camera=\(\)/);
  assert.match(source, /geolocation=\(\)/);

  const response = await renderPath("/");
  assert.equal(response.headers.get("x-frame-options"), "SAMEORIGIN");
  assert.match(response.headers.get("content-security-policy"), /frame-src 'self'/);
});

test("the policy names no host but this one", async () => {
  const response = await renderPath("/");
  const policy = response.headers.get("content-security-policy");

  /* Everything this page loads is served from here: the fonts are self-hosted by
     `next/font`, the scenes are chunks, the choir app is vendored. A host appearing
     in the policy means something started reaching out over the network, which is a
     claim the README makes about this site and would stop being true. */
  assert.doesNotMatch(policy, /https?:\/\//);
  assert.match(policy, /default-src 'self'/);
  assert.match(policy, /object-src 'none'/);
  assert.match(policy, /base-uri 'none'/);

  /* `script-src` carries `'unsafe-inline'` because the server render ships the RSC
     payload as inline script blocks whose content differs on every route and every
     build — no hash list describes them and vinext exposes no nonce. That is a real
     limit and it is written down in `worker/security-headers.ts`; what must not
     happen is `'unsafe-eval'` joining it, or a second origin. */
  assert.doesNotMatch(policy, /unsafe-eval/);
});
