/**
 * Generated by `node scripts/ledger.mjs`. Do not edit.
 *
 * Every number here was counted from the repository it describes: test totals by
 * running the suite and reading its reporter, line and file counts from
 * `git ls-files` filtered to source, dependency counts from each manifest,
 * commit counts from `git rev-list`. Re-run the script rather than editing a
 * figure -- `tests/rendered-html.test.mjs` checks the page against this file.
 */

export type LedgerRepo = (typeof ledger)["repos"][number];

export const ledger = {
  "generatedAt": "2026-07-29",
  "command": "node scripts/ledger.mjs",
  "totals": {
    "projects": 7,
    "tests": 960,
    "lines": 102211,
    "files": 359,
    "commits": 150,
    "extensions": 4,
    "zeroDependencyProjects": 4
  },
  "repos": [
    {
      "slug": "satb-practice",
      "label": "Choir Practice",
      "projectId": "choir-practice",
      "tests": 378,
      "suites": [
        {
          "command": "npm test",
          "passed": 281
        },
        {
          "command": "npm run test:parser",
          "passed": 27
        },
        {
          "command": "npm run e2e",
          "passed": 70
        }
      ],
      "files": 34,
      "lines": 22777,
      "runtimeDependencies": 0,
      "devDependencies": 5,
      "commits": 33,
      "head": "ee8b079"
    },
    {
      "slug": "Decaf",
      "label": "Decaf",
      "projectId": "decaf",
      "tests": 94,
      "suites": [
        {
          "command": "npm test",
          "passed": 94
        }
      ],
      "files": 32,
      "lines": 9763,
      "runtimeDependencies": 0,
      "devDependencies": 1,
      "commits": 8,
      "head": "101c5bf"
    },
    {
      "slug": "pdf-explainer",
      "label": "PDF Explainer",
      "projectId": "pdf-explainer",
      "tests": 153,
      "suites": [
        {
          "command": "npm test",
          "passed": 153
        }
      ],
      "files": 83,
      "lines": 15310,
      "runtimeDependencies": 13,
      "devDependencies": 16,
      "commits": 9,
      "head": "75fa81d"
    },
    {
      "slug": "pagepack-extension",
      "label": "PagePack",
      "projectId": "pagepack",
      "tests": 7,
      "suites": [
        {
          "command": "npm test",
          "passed": 7
        }
      ],
      "files": 30,
      "lines": 10749,
      "runtimeDependencies": 0,
      "devDependencies": 1,
      "commits": 5,
      "head": "bf8e96a"
    },
    {
      "slug": "grt-bus-time",
      "label": "GRT Next Bus",
      "projectId": "grt-next-bus",
      "tests": 12,
      "suites": [
        {
          "command": "npm test",
          "passed": 12
        }
      ],
      "files": 32,
      "lines": 9895,
      "runtimeDependencies": 4,
      "devDependencies": 3,
      "commits": 7,
      "head": "707533d"
    },
    {
      "slug": "n-back",
      "label": "N-Back",
      "projectId": "n-back",
      "tests": 18,
      "suites": [
        {
          "command": "npm test",
          "passed": 18
        }
      ],
      "files": 26,
      "lines": 3215,
      "runtimeDependencies": 6,
      "devDependencies": 7,
      "commits": 13,
      "head": "3854d90"
    },
    {
      "slug": "night-neutralizer",
      "label": "Night Neutralizer",
      "projectId": "night-neutralizer",
      "tests": 298,
      "suites": [
        {
          "command": "npm test",
          "passed": 298
        }
      ],
      "files": 56,
      "lines": 13498,
      "runtimeDependencies": 0,
      "devDependencies": 6,
      "commits": 4,
      "head": "45793cf"
    }
  ],
  "site": {
    "slug": "personal-website",
    "files": 66,
    "lines": 17004,
    "runtimeDependencies": 4,
    "commits": 71,
    "head": "a4ed8d9"
  }
} as const;
