/**
 * Generated by scripts/build-media.mjs. Do not edit by hand.
 *
 * Every image under public/ that the page renders, with its intrinsic size, an
 * average colour for placeholder tinting, and the AVIF srcset built from
 * public/derived.
 */

export type MediaAsset = {
  width: number;
  height: number;
  /** Average colour, shown behind the image while it decodes. */
  tint: string;
  /** AVIF candidates, narrowest first. Absent for sources that are already AVIF. */
  avif?: string;
};

export const mediaManifest: Record<string, MediaAsset> = {
  "/fun/01-coconut.jpg": {
    width: 852,
    height: 1800,
    tint: "#d6dddb",
    avif: "/derived/fun/01-coconut-420.avif 420w, /derived/fun/01-coconut-640.avif 640w, /derived/fun/01-coconut-852.avif 852w",
  },
  "/fun/02-salmon.jpg": {
    width: 1800,
    height: 1350,
    tint: "#c8a467",
    avif: "/derived/fun/02-salmon-420.avif 420w, /derived/fun/02-salmon-640.avif 640w, /derived/fun/02-salmon-1040.avif 1040w, /derived/fun/02-salmon-1800.avif 1800w",
  },
  "/fun/03-bok-choy.jpg": {
    width: 1350,
    height: 1800,
    tint: "#96987a",
    avif: "/derived/fun/03-bok-choy-420.avif 420w, /derived/fun/03-bok-choy-640.avif 640w, /derived/fun/03-bok-choy-1040.avif 1040w, /derived/fun/03-bok-choy-1350.avif 1350w",
  },
  "/fun/04-sky-building.jpg": {
    width: 1350,
    height: 1800,
    tint: "#415763",
    avif: "/derived/fun/04-sky-building-420.avif 420w, /derived/fun/04-sky-building-640.avif 640w, /derived/fun/04-sky-building-1040.avif 1040w, /derived/fun/04-sky-building-1350.avif 1350w",
  },
  "/fun/05-sunset.jpg": {
    width: 1800,
    height: 1350,
    tint: "#796768",
    avif: "/derived/fun/05-sunset-420.avif 420w, /derived/fun/05-sunset-640.avif 640w, /derived/fun/05-sunset-1040.avif 1040w, /derived/fun/05-sunset-1800.avif 1800w",
  },
  "/fun/06-street-sunset.jpg": {
    width: 1800,
    height: 1350,
    tint: "#918577",
    avif: "/derived/fun/06-street-sunset-420.avif 420w, /derived/fun/06-street-sunset-640.avif 640w, /derived/fun/06-street-sunset-1040.avif 1040w, /derived/fun/06-street-sunset-1800.avif 1800w",
  },
  "/fun/07-winter-sunset.jpg": {
    width: 1800,
    height: 1350,
    tint: "#8d6967",
    avif: "/derived/fun/07-winter-sunset-420.avif 420w, /derived/fun/07-winter-sunset-640.avif 640w, /derived/fun/07-winter-sunset-1040.avif 1040w, /derived/fun/07-winter-sunset-1800.avif 1800w",
  },
  "/fun/08-hallway.jpg": {
    width: 1350,
    height: 1800,
    tint: "#8e816e",
    avif: "/derived/fun/08-hallway-420.avif 420w, /derived/fun/08-hallway-640.avif 640w, /derived/fun/08-hallway-1040.avif 1040w, /derived/fun/08-hallway-1350.avif 1350w",
  },
  "/fun/09-mirror-portrait.jpg": {
    width: 1350,
    height: 1800,
    tint: "#332d28",
    avif: "/derived/fun/09-mirror-portrait-420.avif 420w, /derived/fun/09-mirror-portrait-640.avif 640w, /derived/fun/09-mirror-portrait-1040.avif 1040w, /derived/fun/09-mirror-portrait-1350.avif 1350w",
  },
  "/fun/10-cafeteria.jpg": {
    width: 1350,
    height: 1800,
    tint: "#6e6256",
    avif: "/derived/fun/10-cafeteria-420.avif 420w, /derived/fun/10-cafeteria-640.avif 640w, /derived/fun/10-cafeteria-1040.avif 1040w, /derived/fun/10-cafeteria-1350.avif 1350w",
  },
  "/fun/11-flowers.jpg": {
    width: 1800,
    height: 1350,
    tint: "#717c91",
    avif: "/derived/fun/11-flowers-420.avif 420w, /derived/fun/11-flowers-640.avif 640w, /derived/fun/11-flowers-1040.avif 1040w, /derived/fun/11-flowers-1800.avif 1800w",
  },
  "/fun/12-railway.jpg": {
    width: 1800,
    height: 1350,
    tint: "#55535d",
    avif: "/derived/fun/12-railway-420.avif 420w, /derived/fun/12-railway-640.avif 640w, /derived/fun/12-railway-1040.avif 1040w, /derived/fun/12-railway-1800.avif 1800w",
  },
  "/fun/13-niagara-falls.jpg": {
    width: 1800,
    height: 1350,
    tint: "#5c7c9b",
    avif: "/derived/fun/13-niagara-falls-420.avif 420w, /derived/fun/13-niagara-falls-640.avif 640w, /derived/fun/13-niagara-falls-1040.avif 1040w, /derived/fun/13-niagara-falls-1800.avif 1800w",
  },
  "/fun/14-campus-window.jpg": {
    width: 1800,
    height: 1350,
    tint: "#7d8c78",
    avif: "/derived/fun/14-campus-window-420.avif 420w, /derived/fun/14-campus-window-640.avif 640w, /derived/fun/14-campus-window-1040.avif 1040w, /derived/fun/14-campus-window-1800.avif 1800w",
  },
  "/fun/15-tree-portrait.jpg": {
    width: 1800,
    height: 1350,
    tint: "#858b82",
    avif: "/derived/fun/15-tree-portrait-420.avif 420w, /derived/fun/15-tree-portrait-640.avif 640w, /derived/fun/15-tree-portrait-1040.avif 1040w, /derived/fun/15-tree-portrait-1800.avif 1800w",
  },
  "/fun/16-garden-portrait.jpg": {
    width: 1350,
    height: 1800,
    tint: "#7d8466",
    avif: "/derived/fun/16-garden-portrait-420.avif 420w, /derived/fun/16-garden-portrait-640.avif 640w, /derived/fun/16-garden-portrait-1040.avif 1040w, /derived/fun/16-garden-portrait-1350.avif 1350w",
  },
  "/fun/17-city-fountain.jpg": {
    width: 1350,
    height: 1800,
    tint: "#65776f",
    avif: "/derived/fun/17-city-fountain-420.avif 420w, /derived/fun/17-city-fountain-640.avif 640w, /derived/fun/17-city-fountain-1040.avif 1040w, /derived/fun/17-city-fountain-1350.avif 1350w",
  },
  "/fun/clip-01-poster.avif": {
    width: 675,
    height: 900,
    tint: "#8e9e54",
  },
  "/fun/clip-02-poster.avif": {
    width: 675,
    height: 900,
    tint: "#667a82",
  },
  "/fun/clip-03-poster.avif": {
    width: 480,
    height: 854,
    tint: "#d0d3de",
  },
  "/fun/clip-04-poster.avif": {
    width: 506,
    height: 900,
    tint: "#a18d6e",
  },
  "/fun/gym-map.avif": {
    width: 1550,
    height: 1922,
    tint: "#bbb4ac",
  },
  "/fun/gym-map.png": {
    width: 1550,
    height: 1922,
    tint: "#bbb4ac",
    avif: "/derived/fun/gym-map-420.avif 420w, /derived/fun/gym-map-640.avif 640w, /derived/fun/gym-map-1040.avif 1040w, /derived/fun/gym-map-1550.avif 1550w",
  },
  "/fun/human-flag-right-side-poster.avif": {
    width: 360,
    height: 640,
    tint: "#787d79",
  },
  "/fun/pan-fried-fish.avif": {
    width: 3024,
    height: 4032,
    tint: "#605547",
  },
  "/fun/pan-fried-fish.jpg": {
    width: 3024,
    height: 4032,
    tint: "#5f5547",
    avif: "/derived/fun/pan-fried-fish-420.avif 420w, /derived/fun/pan-fried-fish-640.avif 640w, /derived/fun/pan-fried-fish-1040.avif 1040w, /derived/fun/pan-fried-fish-3024.avif 3024w",
  },
  "/hero-face-1600.jpg": {
    width: 1600,
    height: 2133,
    tint: "#6d726c",
    avif: "/derived/hero-face-1600-768.avif 768w, /derived/hero-face-1600-1200.avif 1200w, /derived/hero-face-1600-1600.avif 1600w",
  },
};

export function mediaAsset(src: string): MediaAsset | undefined {
  return mediaManifest[src];
}
