/**
 * Generated by scripts/build-media.mjs. Do not edit by hand.
 *
 * Every image under public/ that the page renders, with its intrinsic size, an
 * average colour for placeholder tinting, and the AVIF srcset built from
 * public/derived.
 */

export type MediaAsset = {
  width: number;
  height: number;
  /** Average colour, shown behind the image while it decodes. */
  tint: string;
  /** AVIF candidates, narrowest first. Absent for sources that are already AVIF. */
  avif?: string;
};

export const mediaManifest: Record<string, MediaAsset> = {
  "/fun/01-coconut.jpg": {
    width: 852,
    height: 1800,
    tint: "#d6dddb",
    avif: "/derived/fun/01-coconut-420.avif 420w, /derived/fun/01-coconut-640.avif 640w, /derived/fun/01-coconut-852.avif 852w",
  },
  "/fun/02-salmon.jpg": {
    width: 1800,
    height: 1350,
    tint: "#c8a467",
    avif: "/derived/fun/02-salmon-420.avif 420w, /derived/fun/02-salmon-640.avif 640w, /derived/fun/02-salmon-1040.avif 1040w, /derived/fun/02-salmon-1800.avif 1800w",
  },
  "/fun/03-bok-choy.jpg": {
    width: 1350,
    height: 1800,
    tint: "#96987a",
    avif: "/derived/fun/03-bok-choy-420.avif 420w, /derived/fun/03-bok-choy-640.avif 640w, /derived/fun/03-bok-choy-1040.avif 1040w, /derived/fun/03-bok-choy-1350.avif 1350w",
  },
  "/fun/04-sky-building.jpg": {
    width: 1350,
    height: 1800,
    tint: "#415763",
    avif: "/derived/fun/04-sky-building-420.avif 420w, /derived/fun/04-sky-building-640.avif 640w, /derived/fun/04-sky-building-1040.avif 1040w, /derived/fun/04-sky-building-1350.avif 1350w",
  },
  "/fun/05-sunset.jpg": {
    width: 1800,
    height: 1350,
    tint: "#796768",
    avif: "/derived/fun/05-sunset-420.avif 420w, /derived/fun/05-sunset-640.avif 640w, /derived/fun/05-sunset-1040.avif 1040w, /derived/fun/05-sunset-1800.avif 1800w",
  },
  "/fun/06-street-sunset.jpg": {
    width: 1800,
    height: 1350,
    tint: "#918577",
    avif: "/derived/fun/06-street-sunset-420.avif 420w, /derived/fun/06-street-sunset-640.avif 640w, /derived/fun/06-street-sunset-1040.avif 1040w, /derived/fun/06-street-sunset-1800.avif 1800w",
  },
  "/fun/07-winter-sunset.jpg": {
    width: 1800,
    height: 1350,
    tint: "#8d6967",
    avif: "/derived/fun/07-winter-sunset-420.avif 420w, /derived/fun/07-winter-sunset-640.avif 640w, /derived/fun/07-winter-sunset-1040.avif 1040w, /derived/fun/07-winter-sunset-1800.avif 1800w",
  },
  "/fun/08-hallway.jpg": {
    width: 1350,
    height: 1800,
    tint: "#8e816e",
    avif: "/derived/fun/08-hallway-420.avif 420w, /derived/fun/08-hallway-640.avif 640w, /derived/fun/08-hallway-1040.avif 1040w, /derived/fun/08-hallway-1350.avif 1350w",
  },
  "/fun/09-mirror-portrait.jpg": {
    width: 1350,
    height: 1800,
    tint: "#332d28",
    avif: "/derived/fun/09-mirror-portrait-420.avif 420w, /derived/fun/09-mirror-portrait-640.avif 640w, /derived/fun/09-mirror-portrait-1040.avif 1040w, /derived/fun/09-mirror-portrait-1350.avif 1350w",
  },
  "/fun/10-cafeteria.jpg": {
    width: 1350,
    height: 1800,
    tint: "#6e6256",
    avif: "/derived/fun/10-cafeteria-420.avif 420w, /derived/fun/10-cafeteria-640.avif 640w, /derived/fun/10-cafeteria-1040.avif 1040w, /derived/fun/10-cafeteria-1350.avif 1350w",
  },
  "/fun/11-flowers.jpg": {
    width: 1800,
    height: 1350,
    tint: "#717c91",
    avif: "/derived/fun/11-flowers-420.avif 420w, /derived/fun/11-flowers-640.avif 640w, /derived/fun/11-flowers-1040.avif 1040w, /derived/fun/11-flowers-1800.avif 1800w",
  },
  "/fun/12-railway.jpg": {
    width: 1800,
    height: 1350,
    tint: "#55535d",
    avif: "/derived/fun/12-railway-420.avif 420w, /derived/fun/12-railway-640.avif 640w, /derived/fun/12-railway-1040.avif 1040w, /derived/fun/12-railway-1800.avif 1800w",
  },
  "/fun/13-niagara-falls.jpg": {
    width: 1800,
    height: 1350,
    tint: "#5c7c9b",
    avif: "/derived/fun/13-niagara-falls-420.avif 420w, /derived/fun/13-niagara-falls-640.avif 640w, /derived/fun/13-niagara-falls-1040.avif 1040w, /derived/fun/13-niagara-falls-1800.avif 1800w",
  },
  "/fun/14-campus-window.jpg": {
    width: 1800,
    height: 1350,
    tint: "#7d8c78",
    avif: "/derived/fun/14-campus-window-420.avif 420w, /derived/fun/14-campus-window-640.avif 640w, /derived/fun/14-campus-window-1040.avif 1040w, /derived/fun/14-campus-window-1800.avif 1800w",
  },
  "/fun/15-tree-portrait.jpg": {
    width: 1800,
    height: 1350,
    tint: "#858b82",
    avif: "/derived/fun/15-tree-portrait-420.avif 420w, /derived/fun/15-tree-portrait-640.avif 640w, /derived/fun/15-tree-portrait-1040.avif 1040w, /derived/fun/15-tree-portrait-1800.avif 1800w",
  },
  "/fun/16-garden-portrait.jpg": {
    width: 1350,
    height: 1800,
    tint: "#7d8466",
    avif: "/derived/fun/16-garden-portrait-420.avif 420w, /derived/fun/16-garden-portrait-640.avif 640w, /derived/fun/16-garden-portrait-1040.avif 1040w, /derived/fun/16-garden-portrait-1350.avif 1350w",
  },
  "/fun/17-city-fountain.jpg": {
    width: 1350,
    height: 1800,
    tint: "#65776f",
    avif: "/derived/fun/17-city-fountain-420.avif 420w, /derived/fun/17-city-fountain-640.avif 640w, /derived/fun/17-city-fountain-1040.avif 1040w, /derived/fun/17-city-fountain-1350.avif 1350w",
  },
  "/fun/clip-01-poster.avif": {
    width: 675,
    height: 900,
    tint: "#8e9e54",
  },
  "/fun/clip-02-poster.avif": {
    width: 675,
    height: 900,
    tint: "#667a82",
  },
  "/fun/clip-03-poster.avif": {
    width: 480,
    height: 854,
    tint: "#d0d3de",
  },
  "/fun/clip-04-poster.avif": {
    width: 506,
    height: 900,
    tint: "#a18d6e",
  },
  "/fun/gym-map.avif": {
    width: 1550,
    height: 1922,
    tint: "#bbb4ac",
  },
  "/fun/gym-map.png": {
    width: 1550,
    height: 1922,
    tint: "#bbb4ac",
    avif: "/derived/fun/gym-map-420.avif 420w, /derived/fun/gym-map-640.avif 640w, /derived/fun/gym-map-1040.avif 1040w, /derived/fun/gym-map-1550.avif 1550w",
  },
  "/fun/human-flag-right-side-poster.avif": {
    width: 360,
    height: 640,
    tint: "#787d79",
  },
  "/fun/pan-fried-fish.avif": {
    width: 3024,
    height: 4032,
    tint: "#605547",
  },
  "/fun/pan-fried-fish.jpg": {
    width: 3024,
    height: 4032,
    tint: "#5f5547",
    avif: "/derived/fun/pan-fried-fish-420.avif 420w, /derived/fun/pan-fried-fish-640.avif 640w, /derived/fun/pan-fried-fish-1040.avif 1040w, /derived/fun/pan-fried-fish-3024.avif 3024w",
  },
  "/hero-face-1440.avif": {
    width: 1440,
    height: 1920,
    tint: "#6d736c",
  },
  "/hero-face-1600.jpg": {
    width: 1600,
    height: 2133,
    tint: "#6d726c",
    avif: "/derived/hero-face-1600-768.avif 768w, /derived/hero-face-1600-1200.avif 1200w, /derived/hero-face-1600-1600.avif 1600w",
  },
  "/hero-face-2200.avif": {
    width: 2200,
    height: 2933,
    tint: "#6d726c",
  },
  "/hero-face-768.avif": {
    width: 768,
    height: 1024,
    tint: "#6d726c",
  },
  "/projects/blokamine-instagram.avif": {
    width: 1600,
    height: 900,
    tint: "#6e7072",
  },
  "/projects/blokamine-instagram.png": {
    width: 1600,
    height: 900,
    tint: "#6d7072",
    avif: "/derived/projects/blokamine-instagram-640.avif 640w, /derived/projects/blokamine-instagram-1024.avif 1024w, /derived/projects/blokamine-instagram-1480.avif 1480w, /derived/projects/blokamine-instagram-1600.avif 1600w",
  },
  "/projects/blokamine-settings.avif": {
    width: 1462,
    height: 1212,
    tint: "#eef1ef",
  },
  "/projects/blokamine-settings.png": {
    width: 1462,
    height: 1212,
    tint: "#eff2ef",
    avif: "/derived/projects/blokamine-settings-640.avif 640w, /derived/projects/blokamine-settings-1024.avif 1024w, /derived/projects/blokamine-settings-1462.avif 1462w",
  },
  "/projects/blokamine-sites.avif": {
    width: 1350,
    height: 1296,
    tint: "#f1f4f2",
  },
  "/projects/blokamine-sites.png": {
    width: 1350,
    height: 1296,
    tint: "#f1f4f2",
    avif: "/derived/projects/blokamine-sites-640.avif 640w, /derived/projects/blokamine-sites-1024.avif 1024w, /derived/projects/blokamine-sites-1350.avif 1350w",
  },
  "/projects/blokamine.avif": {
    width: 1600,
    height: 934,
    tint: "#515051",
  },
  "/projects/blokamine.png": {
    width: 1600,
    height: 934,
    tint: "#505050",
    avif: "/derived/projects/blokamine-640.avif 640w, /derived/projects/blokamine-1024.avif 1024w, /derived/projects/blokamine-1480.avif 1480w, /derived/projects/blokamine-1600.avif 1600w",
  },
  "/projects/choir-demo-poster.avif": {
    width: 1280,
    height: 828,
    tint: "#1b1c2b",
  },
  "/projects/choir-demo-poster.png": {
    width: 1280,
    height: 828,
    tint: "#1b1c2b",
    avif: "/derived/projects/choir-demo-poster-640.avif 640w, /derived/projects/choir-demo-poster-1024.avif 1024w, /derived/projects/choir-demo-poster-1280.avif 1280w",
  },
  "/projects/choir-export.avif": {
    width: 1600,
    height: 1034,
    tint: "#191d2d",
  },
  "/projects/choir-export.png": {
    width: 1600,
    height: 1034,
    tint: "#1a1d2c",
    avif: "/derived/projects/choir-export-640.avif 640w, /derived/projects/choir-export-1024.avif 1024w, /derived/projects/choir-export-1480.avif 1480w, /derived/projects/choir-export-1600.avif 1600w",
  },
  "/projects/choir-focus.avif": {
    width: 1600,
    height: 923,
    tint: "#1b1f37",
  },
  "/projects/choir-focus.png": {
    width: 1600,
    height: 923,
    tint: "#1b1e35",
    avif: "/derived/projects/choir-focus-640.avif 640w, /derived/projects/choir-focus-1024.avif 1024w, /derived/projects/choir-focus-1480.avif 1480w, /derived/projects/choir-focus-1600.avif 1600w",
  },
  "/projects/choir-import.avif": {
    width: 1600,
    height: 1034,
    tint: "#181c2d",
  },
  "/projects/choir-import.png": {
    width: 1600,
    height: 1034,
    tint: "#191c2d",
    avif: "/derived/projects/choir-import-640.avif 640w, /derived/projects/choir-import-1024.avif 1024w, /derived/projects/choir-import-1480.avif 1480w, /derived/projects/choir-import-1600.avif 1600w",
  },
  "/projects/choir-mix.avif": {
    width: 1600,
    height: 1034,
    tint: "#191b2a",
  },
  "/projects/choir-mix.png": {
    width: 1600,
    height: 1034,
    tint: "#191b2a",
    avif: "/derived/projects/choir-mix-640.avif 640w, /derived/projects/choir-mix-1024.avif 1024w, /derived/projects/choir-mix-1480.avif 1480w, /derived/projects/choir-mix-1600.avif 1600w",
  },
  "/projects/choir-overview.avif": {
    width: 1600,
    height: 919,
    tint: "#1c1f37",
  },
  "/projects/choir-overview.png": {
    width: 1600,
    height: 919,
    tint: "#1c1f35",
    avif: "/derived/projects/choir-overview-640.avif 640w, /derived/projects/choir-overview-1024.avif 1024w, /derived/projects/choir-overview-1480.avif 1480w, /derived/projects/choir-overview-1600.avif 1600w",
  },
  "/projects/choir-pitch.avif": {
    width: 1600,
    height: 1034,
    tint: "#191d2c",
  },
  "/projects/choir-pitch.png": {
    width: 1600,
    height: 1034,
    tint: "#1a1d2c",
    avif: "/derived/projects/choir-pitch-640.avif 640w, /derived/projects/choir-pitch-1024.avif 1024w, /derived/projects/choir-pitch-1480.avif 1480w, /derived/projects/choir-pitch-1600.avif 1600w",
  },
  "/projects/choir-practice.avif": {
    width: 1600,
    height: 922,
    tint: "#1e2135",
  },
  "/projects/choir-practice.png": {
    width: 1600,
    height: 922,
    tint: "#1e2136",
    avif: "/derived/projects/choir-practice-640.avif 640w, /derived/projects/choir-practice-1024.avif 1024w, /derived/projects/choir-practice-1480.avif 1480w, /derived/projects/choir-practice-1600.avif 1600w",
  },
  "/projects/choir-scrub.avif": {
    width: 1600,
    height: 1034,
    tint: "#181c2b",
  },
  "/projects/choir-scrub.png": {
    width: 1600,
    height: 1034,
    tint: "#191c2b",
    avif: "/derived/projects/choir-scrub-640.avif 640w, /derived/projects/choir-scrub-1024.avif 1024w, /derived/projects/choir-scrub-1480.avif 1480w, /derived/projects/choir-scrub-1600.avif 1600w",
  },
  "/projects/choir-tempo.avif": {
    width: 1600,
    height: 1034,
    tint: "#191c2c",
  },
  "/projects/choir-tempo.png": {
    width: 1600,
    height: 1034,
    tint: "#191c2c",
    avif: "/derived/projects/choir-tempo-640.avif 640w, /derived/projects/choir-tempo-1024.avif 1024w, /derived/projects/choir-tempo-1480.avif 1480w, /derived/projects/choir-tempo-1600.avif 1600w",
  },
  "/projects/grt-add-stop.avif": {
    width: 830,
    height: 720,
    tint: "#dee8e8",
  },
  "/projects/grt-add-stop.png": {
    width: 830,
    height: 720,
    tint: "#dde9e8",
    avif: "/derived/projects/grt-add-stop-640.avif 640w, /derived/projects/grt-add-stop-830.avif 830w",
  },
  "/projects/grt-alert.avif": {
    width: 760,
    height: 188,
    tint: "#2c2d2f",
  },
  "/projects/grt-alert.png": {
    width: 760,
    height: 188,
    tint: "#2b2d2e",
    avif: "/derived/projects/grt-alert-640.avif 640w, /derived/projects/grt-alert-760.avif 760w",
  },
  "/projects/grt-next-bus.avif": {
    width: 842,
    height: 1200,
    tint: "#f1f4f3",
  },
  "/projects/grt-next-bus.png": {
    width: 842,
    height: 1200,
    tint: "#f1f4f3",
    avif: "/derived/projects/grt-next-bus-640.avif 640w, /derived/projects/grt-next-bus-842.avif 842w",
  },
  "/projects/grt-pro.avif": {
    width: 842,
    height: 1196,
    tint: "#f0f3f2",
  },
  "/projects/grt-pro.png": {
    width: 842,
    height: 1196,
    tint: "#f0f3f2",
    avif: "/derived/projects/grt-pro-640.avif 640w, /derived/projects/grt-pro-842.avif 842w",
  },
  "/projects/nback-game.avif": {
    width: 1600,
    height: 1459,
    tint: "#131616",
  },
  "/projects/nback-game.png": {
    width: 1600,
    height: 1459,
    tint: "#121715",
    avif: "/derived/projects/nback-game-640.avif 640w, /derived/projects/nback-game-1024.avif 1024w, /derived/projects/nback-game-1480.avif 1480w, /derived/projects/nback-game-1600.avif 1600w",
  },
  "/projects/nback-tutorial.avif": {
    width: 1600,
    height: 1527,
    tint: "#111312",
  },
  "/projects/nback-tutorial.png": {
    width: 1600,
    height: 1527,
    tint: "#101312",
    avif: "/derived/projects/nback-tutorial-640.avif 640w, /derived/projects/nback-tutorial-1024.avif 1024w, /derived/projects/nback-tutorial-1480.avif 1480w, /derived/projects/nback-tutorial-1600.avif 1600w",
  },
  "/projects/pagepack-folder.avif": {
    width: 752,
    height: 1186,
    tint: "#242426",
  },
  "/projects/pagepack-folder.png": {
    width: 752,
    height: 1186,
    tint: "#232426",
    avif: "/derived/projects/pagepack-folder-640.avif 640w, /derived/projects/pagepack-folder-752.avif 752w",
  },
  "/projects/pagepack-library.avif": {
    width: 760,
    height: 1194,
    tint: "#2a2a2c",
  },
  "/projects/pagepack-library.png": {
    width: 760,
    height: 1194,
    tint: "#2a2a2c",
    avif: "/derived/projects/pagepack-library-640.avif 640w, /derived/projects/pagepack-library-760.avif 760w",
  },
  "/projects/pagepack-options.avif": {
    width: 758,
    height: 904,
    tint: "#313c4a",
  },
  "/projects/pagepack-options.png": {
    width: 758,
    height: 904,
    tint: "#313c4a",
    avif: "/derived/projects/pagepack-options-640.avif 640w, /derived/projects/pagepack-options-758.avif 758w",
  },
  "/projects/pagepack-reader.avif": {
    width: 1600,
    height: 1002,
    tint: "#deccd2",
  },
  "/projects/pagepack-reader.png": {
    width: 1600,
    height: 1002,
    tint: "#deccd3",
    avif: "/derived/projects/pagepack-reader-640.avif 640w, /derived/projects/pagepack-reader-1024.avif 1024w, /derived/projects/pagepack-reader-1480.avif 1480w, /derived/projects/pagepack-reader-1600.avif 1600w",
  },
  "/projects/pagepack.avif": {
    width: 826,
    height: 1304,
    tint: "#2a2d32",
  },
  "/projects/pagepack.png": {
    width: 826,
    height: 1304,
    tint: "#2a2d32",
    avif: "/derived/projects/pagepack-640.avif 640w, /derived/projects/pagepack-826.avif 826w",
  },
  "/projects/pdf-explainer-demo-poster.avif": {
    width: 1600,
    height: 1034,
    tint: "#151d2a",
  },
  "/projects/pdf-explainer-demo-poster.png": {
    width: 1600,
    height: 1034,
    tint: "#151d2a",
    avif: "/derived/projects/pdf-explainer-demo-poster-640.avif 640w, /derived/projects/pdf-explainer-demo-poster-1024.avif 1024w, /derived/projects/pdf-explainer-demo-poster-1480.avif 1480w, /derived/projects/pdf-explainer-demo-poster-1600.avif 1600w",
  },
  "/projects/pdf-explainer-feature.avif": {
    width: 1600,
    height: 922,
    tint: "#dfe0e1",
  },
  "/projects/pdf-explainer-feature.png": {
    width: 1600,
    height: 922,
    tint: "#dfe0e1",
    avif: "/derived/projects/pdf-explainer-feature-640.avif 640w, /derived/projects/pdf-explainer-feature-1024.avif 1024w, /derived/projects/pdf-explainer-feature-1480.avif 1480w, /derived/projects/pdf-explainer-feature-1600.avif 1600w",
  },
  "/projects/pdf-explainer-interactive-quiz.avif": {
    width: 1780,
    height: 846,
    tint: "#0c1324",
  },
  "/projects/pdf-explainer-interactive-quiz.png": {
    width: 1780,
    height: 846,
    tint: "#0c1324",
    avif: "/derived/projects/pdf-explainer-interactive-quiz-640.avif 640w, /derived/projects/pdf-explainer-interactive-quiz-1024.avif 1024w, /derived/projects/pdf-explainer-interactive-quiz-1480.avif 1480w, /derived/projects/pdf-explainer-interactive-quiz-1780.avif 1780w",
  },
  "/projects/pdf-explainer-match.avif": {
    width: 1374,
    height: 772,
    tint: "#37373b",
  },
  "/projects/pdf-explainer-match.png": {
    width: 1374,
    height: 772,
    tint: "#37373b",
    avif: "/derived/projects/pdf-explainer-match-640.avif 640w, /derived/projects/pdf-explainer-match-1024.avif 1024w, /derived/projects/pdf-explainer-match-1374.avif 1374w",
  },
  "/projects/pdf-explainer-quiz.avif": {
    width: 1600,
    height: 1034,
    tint: "#151b26",
  },
  "/projects/pdf-explainer-quiz.png": {
    width: 1600,
    height: 1034,
    tint: "#151b26",
    avif: "/derived/projects/pdf-explainer-quiz-640.avif 640w, /derived/projects/pdf-explainer-quiz-1024.avif 1024w, /derived/projects/pdf-explainer-quiz-1480.avif 1480w, /derived/projects/pdf-explainer-quiz-1600.avif 1600w",
  },
  "/projects/pdf-explainer-transparency.avif": {
    width: 1600,
    height: 1034,
    tint: "#161d29",
  },
  "/projects/pdf-explainer-transparency.png": {
    width: 1600,
    height: 1034,
    tint: "#161d29",
    avif: "/derived/projects/pdf-explainer-transparency-640.avif 640w, /derived/projects/pdf-explainer-transparency-1024.avif 1024w, /derived/projects/pdf-explainer-transparency-1480.avif 1480w, /derived/projects/pdf-explainer-transparency-1600.avif 1600w",
  },
  "/projects/pdf-explainer-tutor.avif": {
    width: 1600,
    height: 1034,
    tint: "#181f2d",
  },
  "/projects/pdf-explainer-tutor.png": {
    width: 1600,
    height: 1034,
    tint: "#171f2d",
    avif: "/derived/projects/pdf-explainer-tutor-640.avif 640w, /derived/projects/pdf-explainer-tutor-1024.avif 1024w, /derived/projects/pdf-explainer-tutor-1480.avif 1480w, /derived/projects/pdf-explainer-tutor-1600.avif 1600w",
  },
  "/projects/pdf-explainer.avif": {
    width: 1600,
    height: 972,
    tint: "#a5a7ad",
  },
  "/projects/pdf-explainer.png": {
    width: 1600,
    height: 972,
    tint: "#a5a7ad",
    avif: "/derived/projects/pdf-explainer-640.avif 640w, /derived/projects/pdf-explainer-1024.avif 1024w, /derived/projects/pdf-explainer-1480.avif 1480w, /derived/projects/pdf-explainer-1600.avif 1600w",
  },
  "/projects/zen-n-back.avif": {
    width: 1600,
    height: 1467,
    tint: "#1e2421",
  },
  "/projects/zen-n-back.png": {
    width: 1600,
    height: 1467,
    tint: "#1d2421",
    avif: "/derived/projects/zen-n-back-640.avif 640w, /derived/projects/zen-n-back-1024.avif 1024w, /derived/projects/zen-n-back-1480.avif 1480w, /derived/projects/zen-n-back-1600.avif 1600w",
  },
};

export function mediaAsset(src: string): MediaAsset | undefined {
  return mediaManifest[src];
}
